---
title: "iNaturalist"
author: "Jay Matsushiba"
date: "2025/04/25"
format:
  html:
    code-fold: true
---
# iNaturalist Observation Data on Bowen Island
## Setup
```{r setup, output = F}
#### Palen Lab Packages ####
library(bowen.biodiversity.webapp)

#### Other Packages ####
library(here)
library(dplyr)
library(stringr)
library(foreach)
library(sf)
library(terra)
library(tidyterra)
library(readxl)
library(googlesheets4)
```

```{r}
## code to prepare `bowen_inat` dataset goes here
library(sf)
library(terra)
library(tidyverse)

#### Creating sf object from all iNaturalist observations on Bowen Island ####
# Updated as of 2025/09/02
# Load records
bowen_inat_raw <- st_read(here("data-raw/observations-610962.csv"),
                          options=c("X_POSSIBLE_NAMES=longitude","Y_POSSIBLE_NAMES=latitude"))
bowen_inat <- bowen_inat_raw %>%
  st_set_crs(4326) %>%
  dplyr::select(!c("private_longitude", "private_latitude"))

#### Creating raster with iNaturalist observation counts per cell ####
# Matches the Zonation raster cells
# Load Bowen Mask to create raster
bowen_mask <- rast(here("inst/extdata/bowen_mask.tif"))
# Convert sf to vect
bowen_inat_vect <- bowen_inat %>%
  vect() %>%
  project(bowen_mask)
# Count points in each pixel
bowen_inat_count_rast <- terra::rasterize(bowen_inat_vect, bowen_mask, fun = "count") %>%
  mask(bowen_mask) %>% # Mask to cells with Zonation values
  project("EPSG: 3857")

# Plot params
title <- "Bowen Island iNaturalist Observations"
subtitle <- "This map shows the number of iNaturalist observations per 100 m by 100 m cell on Bowen Island. Observations have been up to date as of September 2nd, 2025."
caption <- paste0("Map created: ", date(), ". Palen Lab. Created by Jay Matsushiba (jmatsush@sfu.ca)")
# Output Directory
output_dir <- here("vignettes/figures/inaturalist")
if(!dir.exists(output_dir)) {
  dir.create(output_dir)
}

colours_vect <- c('#feebe2','#fcc5c0','#fa9fb5','#f768a1','#dd3497','#ae017e','#7a0177')
colour_ramp <- colorRamp(colours_vect)

inaturalist_gg <- function() {
  list(
    geom_spatraster(data = bowen_inat_count_rast),
    scale_fill_stepsn(
      name = "iNaturalist Obs.",
      colours = colours_vect,
      na.value = NA,
      transform = "log10", 
      breaks = c(1, 4, 10, 50, 200, 700, 3000),
      labels = c("1 - 4", "4 - 10", "10 - 50", "50 - 200", "200 - 700", "700 - 3000", "3000 - 10000")
    )
  )
}

inaturalist_map <- bowen_map_ggplot(inaturalist_gg,
                                    title = title,
                                    subtitle = subtitle,
                                    caption = caption
)

ggplot2::ggsave(
  here(output_dir, "/", paste0(Sys.Date(), "_inaturalist.png")),
  inaturalist_map,
  device = ragg::agg_png,
  width = 9, height = 12, units = "in", res = 300
)
```

