---
title: "overlap_maps"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{overlap_maps}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bowen.biodiversity.webapp)
library(terra)
library(sf)
library(here)
library(tidyterra)
library(ggplot2)
library(basemaps)
library(dplyr)
```

```{r}
# Zonation5 input layers logic ----
species_df <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1ehO30w4i7EDafilNyRpq3sgc86fm8g_TmYMI4ql3qms/edit?usp=sharing") %>%
  dplyr::rename(layer_name = sci_name)
environmental_df <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1S7U53ukf74y3YaCDZUUSCh2Rv_wpbdZ4veH-BotoQKo/edit?gid=0#gid=0")
# Combine Species and Environmental df for now
layers_df <- dplyr::bind_rows(species_df, environmental_df)
```

# Map Zonation run all environmental and species layers weighted equally (weight of 1.0)
```{r}
# Run Zonation5
zonation5(layers_df)
# Load output from Zonation
zonation_input_path <- here("inst", "app", "zonation", "zonation_input")
zonation_output_path <- here("inst", "app", "zonation", "zonation_output")
zonation_rast <- terra::rast(here::here(zonation_output_path, "rankmap.tif"))
# Plot
bowen_plot <- bowen_map(raster_layer = zonation_rast,
                        title = "Equal Weighted Prioritization of All Environmental and Species Layers",
                        subtitle = "Zonation5 Prioritization Algorithm of Locations on Bowen Island.",
                        caption = paste0("Map created on ", Sys.time(), " by Jay Matsushiba (jmatsush@sfu.ca) in the Palen Lab."),
                        legend_label = "Priority")
# Save plot
output_path <- here::here("vignettes/figures/equal_weight_zonation")
dir.create(output_path)
ggplot2::ggsave(
  paste0(output_path, "/", Sys.Date(), "_equal_weight_zonation.png"),
  bowen_plot,
  device = ragg::agg_png,
  width = 9, height = 12, units = "in", res = 300
)
# Save rankmap.tif, settings.z5, features.txt
file.copy(here::here(zonation_output_path, "rankmap.tif"), 
          here::here(output_path, "rankmap.tif"),
          overwrite = T)
file.copy(here::here(zonation_input_path, "settings.z5"), 
          here::here(output_path, "settings.z5"),
          overwrite = T)
file.copy(here::here(zonation_input_path, "features.txt"), 
          here::here(output_path, "features.txt"),
          overwrite = T)
```


# Map Zonation where environmental layers weighed 50% and species layers weighed 50%
```{r}
n_env_layers <- layers_df %>%
  filter(is.na(taxon_group)) %>%
  nrow()
n_spec_layers <- layers_df %>%
  filter(!is.na(taxon_group)) %>%
  nrow()
split_layers_df <- layers_df %>%
  mutate(
    weights = case_when(
      is.na(taxon_group) ~ 1/n_env_layers,
      !is.na(taxon_group) ~ 1/n_spec_layers
    )
  )
# Run Zonation5
zonation5(split_layers_df)
# Load output from Zonation
zonation_input_path <- here("inst", "app", "zonation", "zonation_input")
zonation_output_path <- here("inst", "app", "zonation", "zonation_output")
zonation_rast <- terra::rast(here::here(zonation_output_path, "rankmap.tif"))
# Plot
bowen_plot <- bowen_map(raster_layer = zonation_rast,
                        title = "Split Weighted Prioritization of All Environmental and Species Layers",
                        subtitle = "Zonation5 Prioritization Algorithm of Locations on Bowen Island. Environmental layers combined weighted 50%, with species layers combined weighted 50%",
                        caption = paste0("Map created on ", Sys.time(), " by Jay Matsushiba (jmatsush@sfu.ca) in the Palen Lab."),
                        legend_label = "Priority")
# Save plot
output_path <- here::here("vignettes/figures/split_weight_zonation")
dir.create(output_path)
ggplot2::ggsave(
  paste0(output_path, "/", Sys.Date(), "_split_weight_zonation.png"),
  bowen_plot,
  device = ragg::agg_png,
  width = 9, height = 12, units = "in", res = 300
)
# Save rankmap.tif, settings.z5, features.txt
file.copy(here::here(zonation_output_path, "rankmap.tif"), 
          here::here(output_path, "rankmap.tif"))
file.copy(here::here(zonation_input_path, "settings.z5"), 
          here::here(output_path, "settings.z5"))
file.copy(here::here(zonation_input_path, "features.txt"), 
          here::here(output_path, "features.txt"))
```



# Equal Weight Zonation Overlap with Human Footprint Map
```{r}
filepath <- here::here("vignettes/figures/equal_weight_zonation/rankmap.tif")
zonation_rast <- terra::rast(filepath)
dir.create(here::here("vignettes/figures/human_footprint"))

top_20_value <- zonation_rast %>%
  values() %>%
  quantile(probs = .8, na.rm = T)

m <- matrix(c(
  0, top_20_value, NA,
  top_20_value, 1, 1
), ncol = 3, byrow = T)
zonation_rast_0.2 <- zonation_rast %>%
  classify(m) 

human_footprint_filepath <- here::here("inst/app/data/bowen_island_env_rasters/bowen_island_normal_inverse_human_footprint.tif")
human_footprint <- terra::rast(here(human_footprint_filepath)) %>%
  terra::project(zonation_rast_0.2) 
# Reverse so that high value (closer to 1) of human footprint means higher disturbance
human_footprint <- (1 - human_footprint)

human_footprint_zonation_0.2 <- zonation_rast_0.2 * human_footprint

# 
human_footprint_plot <- bowen_map(human_footprint_zonation_0.2,
                                    title = "Biodiversity Hotspots and Human Footprint",
                                    subtitle = "Top 20% of biodiversity locations on Bowen Island, with scale corresponding to relative human disturbance. Higher values, towards 1.0, indicate higher levels of disturbance from human activity. Lower values, towards 0.0, show lower levels of disturbance.",
                                    caption = "Jay Matsushiba January 13 2025",
                                    legend_label = "Human Disturbance")

ggplot2::ggsave(
  paste0("figures/human_footprint/", Sys.Date(), "_human_footprint_plot.png"),
  human_footprint_plot,
  device = ragg::agg_png,
  width = 9, height = 12, units = "in", res = 300
)
```

# Equal Weight Zonation Overlap with Protected Areas (including covenants)
```{r}
zonation_path <- here::here("vignettes/figures/equal_weight_zonation/rankmap.tif")
zonation_rast <- terra::rast(zonation_path)
output_path <- here::here("vignettes/figures/protected_areas_overlap")
dir.create(output_path)

protected_areas <- sf::st_read(here::here("inst/app/data/bowen_island_protectedareas")) %>%
  sf::st_make_valid()
covenants <- sf::st_read(here::here("inst/app/data/bowen_island_covenants.gpkg"))  %>%
  sf::st_make_valid()

all_protected_areas <- sf::st_union(protected_areas, covenants)

protected_areas_colour <- "#EE964B"
covenants_colour <- "#AD3800"

zonation_plot <- bowen_map(zonation_rast,
                                    title = "Biodiversity Hotspots and Protected Areas",
                                    subtitle = "Biodiversity hotspots, with gradient scale corresponding to relative priority for conservation. Higher values, towards 1.0, indicate higher priority. Lower values, towards 0.0, show lower priority. Protected Areas, including covenants, are visualized as an overlay on top of the priotization map.",
                                    caption = "Jay Matsushiba January 23 2025",
                                    legend_label = "Priority") +
  geom_sf(data = protected_areas, 
          aes(fill = protected_areas_colour, 
              color = protected_areas_colour), 
          alpha = 0.2,
          linewidth = 1) +
  geom_sf(data = covenants, 
          aes(fill = covenants_colour, 
              colour = covenants_colour), 
          alpha = 0.2,
          linewidth = 1) +
  scale_fill_identity(name = "",
                      breaks = c(protected_areas_colour, covenants_colour),
                      labels = c("Protected Areas", "Covenants"),
                      guide = "legend") +
  scale_colour_identity(name = "",
                        breaks = c(protected_areas_colour, covenants_colour),
                        labels = c("Protected Areas", "Covenants"),
                        guide = "legend")

ggplot2::ggsave(
  paste0("figures/protected_areas_overlap/", Sys.Date(), "_protected_areas_overlap.png"),
  zonation_plot,
  device = ragg::agg_png,
  width = 9, height = 12, units = "in", res = 300
)

```

# Private Land / Municipal / Crown 
```{r}
private_land <- sf::st_read(here::here("inst/app/data/bowen_island_properties"))
```

# Wetlands / Freshwater Lakes 
```{r}

```

