---
title: "species_table"
date: "January 8 2025"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{species_table}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bowen.biodiversity.webapp)
library(here)
library(stringr)
library(dplyr)
library(googlesheets4)
```

```{r download}
# TODO: code to download spatial layers hosted on Google Drive


```


```{r table}
# select only SDMs
features <- list.files(here::here("inst", "app", "rasters", "2024_12_11_SDM_100m_Bowen_Island"),
                       recursive = T)
layers_df <- data.frame(full_path = paste("inst", "app", "rasters", "2024_12_11_SDM_100m_Bowen_Island", features, sep = "/"))

layers_df$filename <- basename(layers_df$full_path)
layers_df$weights <- 1.0
layers_df$sci_name <- layers_df$filename %>%
  gsub("_BowenIsland_100m.tif", "", .) %>%
  gsub("\\.", " ", .)

layers_df$taxon_group <- case_when(
    str_detect(layers_df$full_path, "Fish") ~ "Fish",
    str_detect(layers_df$full_path, "MammalSmall") ~ "MammalSmall",
    str_detect(layers_df$full_path, "Bird") ~ "Bird",
    str_detect(layers_df$full_path, "Amphibian") ~ "Amphibian",
    str_detect(layers_df$full_path, "Reptile") ~ "Reptile"
  )

layers_df$prov_status <- ""
layers_df$fed_status <- ""
layers_df$IUCN_status <- ""

# This sheet was uploaded to Google Sheets
# WARNING: DO NOT RUN OR WILL OVERWRITE MANUAL INPUT TO GOOGLE SHEETS
# write_sheet(layers_df,
#             "https://docs.google.com/spreadsheets/d/1ehO30w4i7EDafilNyRpq3sgc86fm8g_TmYMI4ql3qms/edit?usp=sharing",
#             "species")
# write.csv(layers_df, "species_df.csv")
```

# Read in from Google Sheets as updated by Michael Tylo (Jan 8 2025)
```{r}
layers_googlesheet <- read_sheet("https://docs.google.com/spreadsheets/d/1ehO30w4i7EDafilNyRpq3sgc86fm8g_TmYMI4ql3qms/edit?usp=sharing")
```

# Create plots for each individual species in PNG for review
```{r}
for(n in 1:nrow(layers_df)) {
  full_path <- layers_df[[n, "full_path"]]
  taxon_group <- layers_df[[n, "taxon_group"]]
  sci_name <- layers_df[[n, "sci_name"]]

  layer <- here::here(full_path) %>%
    terra::rast()

  output_map <- bowen_map(raster_layer = layer,
                          title = sci_name,
                          subtitle = paste0("Species of ", taxon_group, ". Species Distribution Model."),
                          legend_label = "Probability",
                          caption = "Created by Jay Matsushiba (jmatsush@sfu.ca) for Palen Lab. January 21 2025.")
  
  ggplot2::ggsave(
    paste0("figures/individual_species_maps/", taxon_group, "/", sci_name, ".png"),
    output_map,
    device = ragg::agg_png,
    width = 9, height = 12, units = "in", res = 300
  )
}

```


