---
title: "threats_development"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{threats_development}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bowen.biodiversity.webapp)
library(sf)
library(terra)
library(here)
library(tidyverse)
library(leaflet)
```

# Exploring data
```{r eval=FALSE}
bca_folio_addresses <- here("data-raw/bc_assessment/data_advice_COMP22_20220101/bca_folio_addresses_20220101_COMP22.csv") %>%
  read.csv()

bowen_folio_addresses <- bca_folio_addresses[bca_folio_addresses$JURISDICTION_CODE == 321,]
bowen_folio_grnl_property_values <- here("data-raw/bc_assessment/data_advice_COMP22_20220101/bca_folio_gnrl_property_values_20220101_COMP22.csv") %>%
  read.csv() %>%
  filter(JURISDICTION_CODE == 321)

# ParcelMapBC filtered to Bowen Island, Municipality in QGIS 
bowen_parcelmap <- here("data-raw/bowen_parcelmap.gpkg") %>% 
  st_read()

# Spatial data, query by Jurisdiction Code (321 for Bowen Island)
bca_folios <- here("data-raw/bc_assessment/bca_folios_spatial_file_20230103/bca_folios.gpkg.gpkg") %>%
  st_read(query = 'SELECT * FROM WHSE_HUMAN_CULTURAL_ECONOMIC_BCA_FOLIO_GNRL_PROP_VALUES_SV WHERE JURISDICTION_CODE LIKE 321')


# Sales data
bca_sales_history <- here("data-raw/bc_assessment/bca_folios_spatial_file_20230103/bca_folios.gpkg.gpkg") %>%
  st_read(query = 'SELECT * FROM WHSE_HUMAN_CULTURAL_ECONOMIC_BCA_FOLIO_SALES_SV WHERE JURISDICTION_CODE LIKE 321')


```

# BCA sales data
```{r}
bowen_sales_history <- here("data-raw/bc_assessment/bca_folios_spatial_file_20230103/bca_folios.gpkg.gpkg") %>%
  st_read(query = 'SELECT * FROM WHSE_HUMAN_CULTURAL_ECONOMIC_BCA_FOLIO_SALES_SV WHERE JURISDICTION_CODE LIKE 321')

# Assumes that first date is lowest price, last date is highest price
bowen_sales_summary  <- bowen_sales_history %>%
  st_drop_geometry() %>%
  filter(CONVEYANCE_TYPE_DESCRIPTION != "Reject - Not Suitable for Sales Analysis") %>%
  group_by(FOLIO_ID) %>%
  summarise(first_date = min(CONVEYANCE_DATE),
            last_date = max(CONVEYANCE_DATE),
            lowest_price = min(CONVEYANCE_PRICE),
            highest_price = max(CONVEYANCE_PRICE),
            n_distinct = n_distinct(CONVEYANCE_TYPE_DESCRIPTION)
            ) %>%
  mutate(change_type = case_when(n_distinct > 1 ~ "changed", .default = "unchanged")) %>%
  mutate(days_span = as.double(last_date - first_date, units = "days")) %>% 
  mutate(price_days_slope = (highest_price - lowest_price)/days_span) %>% 
  filter(!is.infinite(price_days_slope) & !is.na(price_days_slope))

ggplot(bowen_sales_summary) +
  geom_segment(aes(x = first_date, xend = last_date, y = lowest_price, yend = highest_price, colour = change_type), alpha = 0.2) +
  xlab("Dates") +
  ylab("Price")

# Join with spatial data
bowen_folio_addresses <- here("data-raw/bc_assessment/bca_folios_spatial_file_20230103/bca_folios.gpkg.gpkg") %>%
  st_read(query = 'SELECT * FROM WHSE_HUMAN_CULTURAL_ECONOMIC_BCA_FOLIO_ADDRESSES_SV WHERE JURISDICTION_CODE LIKE 321') 

bowen_sales_summary_sf <- merge(bowen_sales_summary, bowen_folio_addresses) %>%
  rename(geometry = geom) %>%
  st_as_sf() %>%
  st_transform(4326)

# LEAFLET
bins <- c(0, 10, 20, 50, 100, 200, 500, 1000, Inf)
pal <- colorBin("YlOrRd", domain = bowen_sales_summary_sf$price_days_slope, bins = bins)
leaflet(bowen_sales_summary_sf) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(color = "#444444", weight = 0.5,,
              fillColor = ~pal(price_days_slope),
              fillOpacity = 0.7
              ) %>%
  addLegend(pal = pal, values = ~price_days_slope)
```

